[launcher]
version = 1.0.1
description = Based on FOCUS™ Specification
author = Ing. Victor Hasler, Msc

[id]
version = 1.0.1
name = vhc_TA_focus

[install]
is_configured = false
state = enabled

[package]
id = vhc_TA_focus
check_for_updates = false

[ui]
label = FOCUS™ TA for FinOps
is_visible = true

[triggers]
reload.eventgen = true
reload.custom = true