##### Sourcetypes: 
# focus:json      - Standard sourcetype for json formated file ingestions
# focus:csv       - Standard sourcetype for manuall csv file ingestions 
# azure:focus:csv - for Azure ingestion automatic split in --> azure:focus:csv:v10r2 (FOCUS version 1.1) || azure:focus:csv:v12 (FOCUS version 1.2)
#
[focus]
search = `focus_index` sourcetype=focus:json OR sourcetype=focus:csv OR sourcetype=azure:focus:csv:v10r2 OR sourcetype=azure:focus:csv:v12
