# for splunk cloud set the index manually
#[focus_sample]
#homePath = $SPLUNK_DB/focus_sample/db
#coldPath = $SPLUNK_DB/focus_sample/colddb
#thawedPath = $SPLUNK_DB/focus_sample/thaweddb

# for splunk cloud set the index manually
#[finops]
#homePath = $SPLUNK_DB/finops/db
#coldPath = $SPLUNK_DB/finops/colddb
#thawedPath = $SPLUNK_DB/finops/thaweddb