# for splunk cloud you have to setup the index manually
[focus_sample]
homePath = $SPLUNK_DB/focus_sample/db
coldPath = $SPLUNK_DB/focus_sample/colddb
thawedPath = $SPLUNK_DB/focus_sample/thaweddb

[finops]
homePath = $SPLUNK_DB/finops/db
coldPath = $SPLUNK_DB/finops/colddb
thawedPath = $SPLUNK_DB/finops/thaweddb