[shclustering]
conf_replication_include.props = true
conf_replication_include.transforms = true
conf_replication_include.datamodels = true
conf_replication_include.macros = true
conf_replication_include.tags = true
conf_replication_include.eventtypes = true
conf_replication_include.lookups = true
conf_replication_include.savedsearches = true
conf_replication_include.views = true
conf_replication_include.navigation = true
conf_replication_include.app = true
conf_replication_include.eventgen = true